#################################################
# Temperature sensors for use in ESPHome firmwares
#################################################

- sensor:

  - name: for_esphome_temp_in_livingroom
    unique_id: aa4787d2-8f5e-47fa-a6cc-ff3228ae53ec
    unit_of_measurement: °C
    device_class: temperature
    state: "{{ states('sensor.0x158d0003230618_temperature') }}"

  - name: for_esphome_temp_in_bedroom
    unique_id: 9b9cffb0-6bcf-41b4-816d-c3429bb7ab78
    unit_of_measurement: °C
    device_class: temperature
    state: "{{ states('sensor.0x158d0003931b0e_temperature') }}"

  - name: for_esphome_temp_in_nursery
    unique_id: 39a52ebf-aa54-427f-9e6a-69d98de72cdc
    unit_of_measurement: °C
    device_class: temperature
    state: "{{ states('sensor.0x158d0003931aec_temperature') }}"