substitutions:
  board_name: smartir_02
  esp_platform: ESP8266
  esp_board: esp01_1m
  room_name: bedroom

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

esphome:
  includes: 
    - include/daikin_ir.h
  libraries:
    - IRremoteESP8266

# Use the blue LED as a status light.
#   Blink slowly = Temporary issue (WiFi/MQTT disconnected, sensor unavailable, ...)
#   Blink quickly = Error encountered
status_led:
  pin: 
    number: GPIO4

#remote_receiver:
#  id: rcvr
#  pin: 
#    number: GPIO5
#    inverted: True
#  dump: all

remote_transmitter:
  pin:
    number: GPIO14
    inverted: false
  carrier_duty_percent: 50%

sensor:
  - platform: homeassistant
    name: "Current temperature"
    entity_id: sensor.for_esphome_temp_in_${room_name}
    id: ha_temp_${room_name}
    internal: true
    unit_of_measurement: Â°C
    accuracy_decimals: 1

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    internal: true
    name: ${board_name}_button
    id: button

switch:
  - platform: template
    name: ${board_name}_tv_samsung_power
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF
  - platform: template
    name: ${board_name}_tv_samsung_volume_up
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0E01F
  - platform: template
    name: ${board_name}_tv_samsung_volume_down
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0D02F
  - platform: template
    name: ${board_name}_tv_samsung_channel_up
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E048B7
  - platform: template
    name: ${board_name}_tv_samsung_channel_down
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E008F7
  - platform: template
    name: ${board_name}_tv_samsung_mute
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0F00F
  - platform: template
    name: ${board_name}_tv_samsung_play
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0E21D
  - platform: template
    name: ${board_name}_tv_samsung_pause
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E052AD
  - platform: template
    name: ${board_name}_tv_samsung_stop
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0629D
  - platform: template
    name: ${board_name}_tv_samsung_rewind
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0A25D
  - platform: template
    name: ${board_name}_tv_samsung_fastforward
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E012ED
  - platform: template
    name: ${board_name}_tv_samsung_up
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E006F9
  - platform: template
    name: ${board_name}_tv_samsung_down
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E08679
  - platform: template
    name: ${board_name}_tv_samsung_left
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0A659
  - platform: template
    name: ${board_name}_tv_samsung_right
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E046B9
  - platform: template
    name: ${board_name}_tv_samsung_enter
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E016E9
  - platform: template
    name: ${board_name}_tv_samsung_return
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E01AE5
  - platform: template
    name: ${board_name}_tv_samsung_exit
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0B44B
  - platform: template
    name: ${board_name}_tv_samsung_source
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0807F
  - platform: template
    name: ${board_name}_tv_samsung_media_p
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E031CE
  - platform: template
    name: ${board_name}_tv_samsung_smarthub
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E09E61
  - platform: template
    name: ${board_name}_tv_samsung_menu
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E058A7
  - platform: template
    name: ${board_name}_tv_samsung_tools
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0D22D
  - platform: template
    name: ${board_name}_tv_samsung_red_a
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E036C9
  - platform: template
    name: ${board_name}_tv_samsung_green_b
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E028D7
  - platform: template
    name: ${board_name}_tv_samsung_yellow_c
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0A857
  - platform: template
    name: ${board_name}_tv_samsung_blue_d
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E06897

climate:
  - platform: custom
    lambda: |-
      auto daikinac = new DaikinAC();
      daikinac->set_sensor(id(ha_temp_${room_name}));
      App.register_component(daikinac);
      return {daikinac};
    climates:
      - name: "Daikin Bedroom"
      #receiver_id: rcvr