substitutions:
  board_name: sonoff_basic_02
  esp_platform: ESP8266
  esp_board: esp01_1m
  room_name: Bathroom

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

esphome:
  on_boot:
    - switch.turn_off: btn

web_server:
  port: 80

binary_sensor:
  # Button
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${board_name}_button_state"
    on_press:
      - switch.toggle: btn

switch:
  # Relay switch
  - platform: gpio
    id: relay
    pin: GPIO12
    restore_mode: ALWAYS_OFF

  # Template switch for button
  - platform: template
    name: "${board_name}_switch"
    optimistic: true
    id: btn
    turn_on_action:
    - switch.turn_on: relay
#    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
#    - light.turn_off: led

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "${board_name}_led"
    output: basic_green_led
    id: led